### ISSUE TITLE
tidyselect 1.0 and nationwider

### ISSUE THREAD

**Issue by lionel-** [kvasilopoulos/nationwider#1]
Hello,

I'm working through the revdepchecks of tidyselect for the 1.0 release and I see this error:

```r
# Install dev version
remotes::install_github("tidyverse/tidyselect")

ntwd_get("seasonal_regional")
#> Error: Names repair functions can't return `NA` values.
```

The `gather()` call in https://github.com/kvasilopoulos/nationwider/blob/b39fb5ed01b3fb822e204729e8f21670eedd9b99/R/format.R#L126 is failing. That's because the `set_names()` call on line 125 sets a names vector that is one element too short for its input. Tidyselect 1.0 performs a stronger names checking and now forbids `NA` names, which explains the error.

I have opened an issue to make `set_names()` fail when the length doesn't match, which will help catching this kind of errors earlier: https://github.com/r-lib/rlang/issues/886.

In the mean time, it'd be very helpful if you could fix this before the tidyselect release which is planned for January 23.

**Comment by kvasilopoulos** [comment]
The timing is perfect. I already was preparing a minor update for the package, so I will include a fix right away. 

Thanks for letting me know!

**Comment by kvasilopoulos** [comment]
Fixed in https://github.com/kvasilopoulos/nationwider/commit/e7335783f2a4e7551e36410941f10ef66d5c0fad
